/** Source: QB-audit rubrics.pdf pp. 2–11; wrapped words restored, wording unchanged. */
export const RUBRIC_VERSION = "qb-audit-pdf-v1";
export const SECTIONS = [
  { id: "A", title: "Question Bank Structure and Metadata", criteria: [
    "Serial number assigned to every question",
    "Question statement available for every entry",
    "CO assigned to every question",
    "RBT level assigned to every question",
    "PI assigned to every question",
    "Marks assigned to every question",
    "Question type identified (Theory/Numerical)",
    "Module mapping available for every question",
    "No mandatory field left blank",
    "Question bank format consistently maintained",
  ] },
  { id: "B", title: "Module Coverage and Syllabus Alignment", criteria: [
    "All modules represented in the question bank",
    "Questions mapped only to prescribed modules",
    "Module coverage aligns with syllabus structure",
    "Core topics covered in every module",
    "No module significantly underrepresented",
    "No module excessively represented",
    "Module–CO mapping follows Table 1",
    "Latest syllabus revision followed",
    "Module-wise question count documented",
    "Syllabus-question mapping available",
  ] },
  { id: "C", title: "Course Outcome (CO) Alignment", criteria: [
    "Every question mapped to a CO",
    "All COs represented in the question bank",
    "CO distribution documented",
    "Adequate question pool available for each CO",
    "Questions reflect intended CO requirements",
    "No CO significantly underrepresented",
    "No CO excessively represented",
    "Marks distribution across COs documented",
    "CO attainment can be measured through questions",
    "CO mapping sheet available",
  ] },
  { id: "D", title: "RBT Distribution and Cognitive Coverage", criteria: [
    "RBT level assigned to every question",
    "Remember-level questions available",
    "Understand-level questions available",
    "Apply-level questions available",
    "Analyze/Evaluate/Create-level questions available",
    "Higher-order thinking questions included",
    "Balanced distribution across RBT levels",
    "RBT level appropriate to assigned marks",
    "RBT distribution documented",
    "RBT mapping verified",
  ] },
  { id: "E", title: "PI Alignment and Traceability", criteria: [
    "PI assigned to every question",
    "PI mapping follows approved course plan",
    "All relevant PIs represented",
    "Adequate question pool available for each PI",
    "Questions support PI assessment",
    "PI distribution documented",
    "No PI excessively represented",
    "No PI significantly underrepresented",
    "PI mapping sheet available",
    "PI assessment traceability maintained",
  ] },
  { id: "F", title: "Theory-Numerical Distribution", criteria: [
    "Every question classified as Theory or Numerical",
    "Module-wise theory percentage documented",
    "Module-wise numerical percentage documented",
    "Module-wise distribution follows Table 2",
    "Overall theory percentage documented",
    "Overall numerical percentage documented",
    "Overall distribution follows Table 3",
    "Adequate theory question pool available",
    "Adequate numerical question pool available",
    "Theory–Numerical analysis report available",
  ] },
  { id: "G", title: "Marks and Difficulty Consistency", criteria: [
    "Marks assigned to every question",
    "Marks appropriate to question complexity",
    "Marks appropriate to RBT level",
    "Marks consistent across similar questions",
    "Theory question marks appropriately assigned",
    "Numerical question marks appropriately assigned",
    "Easy-level questions available",
    "Moderate-level questions available",
    "Difficult-level questions available",
    "Difficulty distribution documented",
  ] },
  { id: "H", title: "Question Quality and Clarity", criteria: [
    "Questions clearly worded",
    "No ambiguity in interpretation",
    "Appropriate action verbs used",
    "Correct grammar and language used",
    "Technical terminology used correctly",
    "Consistent terminology maintained",
    "Diagrams/data clearly presented",
    "Correct units and symbols used",
    "Instructions complete and clear",
    "Questions academically accurate",
  ] },
  { id: "I", title: "Question Bank Integrity and Moderation", criteria: [
    "Question bank reviewed by subject expert",
    "Internal moderation completed",
    "Questions verified for originality",
    "No duplicate questions identified",
    "No out-of-syllabus questions identified",
    "Academic integrity verified",
    "Documentation maintained",
    "Approval records available",
    "Audit-ready records maintained",
    "Question bank approved by competent authority",
  ] },
  { id: "J", title: "Question Bank Adequacy and Readiness", criteria: [
    "Adequate question pool available across all modules",
    "Adequate question pool available across all COs",
    "Adequate theory question pool available",
    "Adequate numerical question pool available",
    "Adequate higher-RBT question pool available",
    "Question bank supports multiple assessment cycles",
    "Documentation complete",
    "Assessment blueprint requirements satisfied",
    "Question bank ready for academic use",
    "Final approval granted",
  ] },
] as const;

export const CRITERIA = SECTIONS.flatMap(section => section.criteria.map((text, i) => ({
  id: `${section.id}${i + 1}`, section: section.id, text, points: 10 as const,
})));
